-- Facilities Dummy Data
-- Meeting Rooms: 1-3 (3 rooms)
-- Laptop Seats: 1-70 (70 seats)
BEGIN TRANSACTION;
-- Meeting Rooms (resource_type = 'MEETING_ROOM')
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('MEETING_ROOM', 1, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('MEETING_ROOM', 2, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('MEETING_ROOM', 3, 1);

-- Laptop Seats (resource_type = 'LAPTOP_SEAT')
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 1, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 2, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 3, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 4, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 5, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 6, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 7, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 8, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 9, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 10, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 11, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 12, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 13, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 14, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 15, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 16, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 17, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 18, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 19, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 20, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 21, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 22, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 23, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 24, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 25, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 26, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 27, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 28, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 29, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 30, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 31, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 32, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 33, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 34, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 35, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 36, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 37, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 38, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 39, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 40, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 41, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 42, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 43, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 44, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 45, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 46, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 47, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 48, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 49, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 50, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 51, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 52, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 53, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 54, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 55, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 56, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 57, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 58, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 59, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 60, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 61, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 62, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 63, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 64, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 65, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 66, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 67, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 68, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 69, 1);
INSERT INTO facilities (resource_type, resource_number, is_active) VALUES ('LAPTOP_SEAT', 70, 1);
COMMIT;
